<span style="font-size:3em;"> Analysis of the global plant-based meat market </span> 

This is an analysis of the global plant-based meat market, that take into consideration the following three axes for each country: water shortages, the meat consumption in relation to the production and the percentage of vegetarians, creating a coefficient to predict which country will be more suited to the market. 

The following notebook is the cleaning and prep of the population growth part. 
This CSV file, along to the other parts of the analysis, has been used to build a dashbord in Tableau, that you can find here:
https://public.tableau.com/app/profile/rossana.coro/viz/VegetalMeatProject/Accueil

In [589]:
import pandas as pd
import numpy as np
import re

In [590]:
#Import csv file from folder
dataset_brut = pd.read_csv("/Users/rossana/Desktop/demoday/fichiers bruts/Population_growth.csv",sep=';')
dataset_brut.head()

/var/folders/sv/nvyrkmfj1bjb805g76mpfkyw0000gp/T/ipykernel_12416/2995890301.py:2: DtypeWarning: Columns (3,29,50,51,52,53,54,56,57,58,59,60,61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset_brut = pd.read_csv("/Users/rossana/Desktop/demoday/fichiers bruts/Population_growth.csv",sep=';')


Index    Variant Region, subregion, country or area * Notes  Location code  \
0      1  Estimates                                WORLD   NaN            900   
1      2  Estimates                                WORLD   NaN            900   
2      3  Estimates                                WORLD   NaN            900   
3      4  Estimates                                WORLD   NaN            900   
4      5  Estimates                                WORLD   NaN            900   

  ISO3 Alpha-code ISO2 Alpha-code  SDMX code**   Type  Parent code  ...  \
0             NaN             NaN          1.0  World            0  ...   
1             NaN             NaN          1.0  World            0  ...   
2             NaN             NaN          1.0  World            0  ...   
3             NaN             NaN          1.0  World            0  ...   
4             NaN             NaN          1.0  World            0  ...   

   Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)  \
0                                                581                               
1                                                567                               
2                                                546                               
3                                                536                               
4                                                523                               

   Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)  \
0                                                498                                   
1                                                490                                   
2                                                477                                   
3                                                470                                   
4                                                458                                   

  Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)  \
0                                                240                                            
1                                                231                                            
2                                                219                                            
3                                                213                                            
4                                                206                                            

  Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)  \
0                                                272                                           
1                                                258                                           
2                                                240                                           
3                                                233                                           
4                                                224                                           

  Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)  \
0                                                208                                               
1                                                204                                               
2                                                197                                               
3                                                193                                               
4                                                187                                               

  Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)  \
0                                                379                                            
1                                                368                        

In [591]:
# Check values
dataset_brut.columns.values

array(['Index', 'Variant', 'Region, subregion, country or area *',
       'Notes', 'Location code', 'ISO3 Alpha-code', 'ISO2 Alpha-code',
       'SDMX code**', 'Type', 'Parent code', 'Year', 'Total Population',
       'Total Population.1', 'Male Population, as of 1 July (thousands)',
       'Female Population, as of 1 July (thousands)',
       'Population Density, as of 1 July (persons per square km)',
       'Population Sex Ratio, as of 1 July (males per 100 females)',
       'Median Age, as of 1 July (years)',
       'Natural Change, Births minus Deaths (thousands)',
       'Rate of Natural Change (per 1,000 population)',
       'Population Change (thousands)',
       'Population Growth Rate (percentage)',
       'Population Annual Doubling Time (years)', 'Births (thousands)',
       'Births by women aged 15 to 19 (thousands)',
       'Crude Birth Rate (births per 1,000 population)',
       'Total Fertility Rate (live births per woman)',
       'Net Reproduction Rate (surviving daugh

In [592]:
#Delete unuseful column
dataset_pop= dataset_brut.drop(columns=['Index', 'Variant',
       'Notes', 'Location code', 'ISO2 Alpha-code',
       'SDMX code**', 'Type', 'Parent code',
       'Male Population, as of 1 July (thousands)','Total Population.1',
       'Female Population, as of 1 July (thousands)',
       'Population Density, as of 1 July (persons per square km)',
       'Population Sex Ratio, as of 1 July (males per 100 females)',
       'Median Age, as of 1 July (years)',
       'Natural Change, Births minus Deaths (thousands)',
       'Rate of Natural Change (per 1,000 population)',
       'Population Change (thousands)',
       'Population Growth Rate (percentage)',
       'Population Annual Doubling Time (years)', 'Births (thousands)',
       'Births by women aged 15 to 19 (thousands)',
       'Crude Birth Rate (births per 1,000 population)',
       'Total Fertility Rate (live births per woman)',
       'Net Reproduction Rate (surviving daughters per woman)',
       'Mean Age Childbearing (years)',
       'Sex Ratio at Birth (males per 100 female births)',
       'Total Deaths (thousands)', 'Male Deaths (thousands)',
       'Female Deaths (thousands)',
       'Crude Death Rate (deaths per 1,000 population)',
       'Life Expectancy at Birth, both sexes (years)',
       'Mortality between Age 15 and 60, both sexes (deaths under age 60 per 1,000 alive at age 15)',
       'Male Mortality between Age 15 and 60 (deaths under age 60 per 1,000 males alive at age 15)',
       'Female Mortality between Age 15 and 60 (deaths under age 60 per 1,000 females alive at age 15)',
       'Net Number of Migrants (thousands)',
       'Net Migration Rate (per 1,000 population)',
       'Male Life Expectancy at Birth (years)','Female Life Expectancy at Birth (years)',	
       'Life Expectancy at Age 15, both sexes (years)','Male Life Expectancy at Age 15 (years)',	
       'Female Life Expectancy at Age 15 (years)','Life Expectancy at Age 65, both sexes (years)','Under-Five Mortality (deaths under age 5 per 1,000 live births)',
    'Mortality before Age 40, both sexes (deaths under age 40 per 1,000 live births)',	'Male Mortality before Age 40 (deaths under age 40 per 1,000 male live births)',	
    'Female Mortality before Age 40 (deaths under age 40 per 1,000 female live births)','Mortality before Age 60, both sexes (deaths under age 60 per 1,000 live births)',
    'Male Mortality before Age 60 (deaths under age 60 per 1,000 male live births)','Female Mortality before Age 60 (deaths under age 60 per 1,000 female live births)','Mortality between Age 15 and 50, both sexes (deaths under age 50 per 1,000 alive at age 15)',
    'Male Mortality between Age 15 and 50 (deaths under age 50 per 1,000 males alive at age 15)',
    'Female Mortality between Age 15 and 50 (deaths under age 50 per 1,000 females alive at age 15)',
    'Male Life Expectancy at Age 65 (years)','Female Life Expectancy at Age 65 (years)',
    'Life Expectancy at Age 80, both sexes (years)','Male Life Expectancy at Age 80 (years)','Female Life Expectancy at Age 80 (years)',
    'Infant Deaths, under age 1 (thousands)','Infant Mortality Rate (infant deaths per 1,000 live births)','Live Births Surviving to Age 1 (thousands)','Under-Five Deaths, under age 5 (thousands)'
])
dataset_pop.head()

Region, subregion, country or area * ISO3 Alpha-code  Year  Total Population
0                                WORLD             NaN  1950           2477675
1                                WORLD             NaN  1951           2520970
2                                WORLD             NaN  1952           2565291
3                                WORLD             NaN  1953           2615251
4                                WORLD             NaN  1954           2665307

In [593]:
dataset_pop['Total Population'].head()

0    2477675
1    2520970
2    2565291
3    2615251
4    2665307
Name: Total Population, dtype: int64

In [594]:
#check column 'ISO3 Alpha-code'
dataset_pop['ISO3 Alpha-code'].unique()

array([nan, 'SEN', 'URY', 'ARM', 'JAM', 'PNG', 'LAO', 'PRI', 'PAN', 'NOR',
       'LBY', 'HTI', 'DNK', 'NIC', 'GEO', 'PRY', 'SRB', 'MOZ', 'ISR',
       'BDI', 'PRT', 'BOL', 'BEL', 'AZE', 'SYR', 'HUN', 'NLD', 'UZB',
       'BFA', 'CUB', 'TUN', 'KHM', 'TZA', 'GHA', 'YEM', 'PRK', 'ARG',
       'KOR', 'MMR', 'POL', 'IRN', 'FRA', 'SVK', 'MLI', 'MYS', 'HND',
       'DZA', 'NER', 'BLR', 'CZE', 'SOM', 'IRQ', 'MAR', 'LVA', 'BWA',
       'KGZ', 'MNG', 'LBN', 'ALB', 'CAF', 'MDA', 'HRV', 'BEN', 'SLV',
       'ARE', 'KEN', 'GIN', 'AGO', 'SGP', 'AUT', 'PER', 'COM', 'STP',
       'KWT', 'LCA', 'WSM', 'ESH', 'BHR', 'NCL', 'GUM', 'MDV', 'ISL',
       'CUW', 'BRN', 'BLZ', 'VUT', 'BHS', 'MAC', 'SLB', 'MYT', 'BTN',
       'GUF', 'CPV', 'PYF', 'BRB', 'SUR', 'GLP', 'MTQ', 'GNQ', 'SWZ',
       'REU', 'GMB', 'LUX', 'MLT', 'DJI', 'FJI', 'MNE', 'TLS', 'QAT',
       'GAB', 'CYP', 'GNB', 'MUS', 'OMN', 'LSO', 'TTO', 'NAM', 'GUY',
       'GGY', 'IMN', 'JEY', 'ATG', 'ABW', 'DMA', 'VCT', 'BMU', 'KIR',
       'FSM', '

In [595]:
#check column 'Region, subregion, country or area *'
dataset_pop['Region, subregion, country or area *'].unique()

array(['WORLD', 'Sub-Saharan Africa', 'Northern Africa and Western Asia',
       'Central and Southern Asia', 'Eastern and South-Eastern Asia',
       'Latin America and the Caribbean',
       'LATIN AMERICA AND THE CARIBBEAN',
       'Oceania (excluding Australia and New Zealand)', 'Senegal',
       'Uruguay', 'Armenia', 'Jamaica', 'Papua New Guinea',
       "Lao People's Democratic Republic", 'Puerto Rico', 'Panama',
       'Norway', 'Libya', 'Haiti', 'Denmark', 'Nicaragua', 'Georgia',
       'Paraguay', 'Serbia', 'Mozambique', 'Israel', 'Burundi',
       'Portugal', 'Bolivia (Plurinational State of)', 'Belgium',
       'Azerbaijan', 'Syrian Arab Republic', 'Hungary', 'Netherlands',
       'Australia/New Zealand', 'Uzbekistan', 'Burkina Faso',
       'No income group available', 'Cuba', 'Tunisia', 'Cambodia',
       'United Republic of Tanzania', 'OCEANIA', 'Ghana', 'Yemen',
       "Dem. People's Republic of Korea", 'Argentina',
       'Republic of Korea', 'Europe and Northern Americ

In [596]:
# Rename the remaining columns.
dataset_pop=dataset_pop.rename(columns={"ISO3 Alpha-code": "Location_code","Region, subregion, country or area *":"Regions","Total Population, as of 1 July (thousands)":"Total Population"})
dataset_pop.head()

Regions Location_code  Year  Total Population
0   WORLD           NaN  1950           2477675
1   WORLD           NaN  1951           2520970
2   WORLD           NaN  1952           2565291
3   WORLD           NaN  1953           2615251
4   WORLD           NaN  1954           2665307

In [597]:
dataset_pop['Total Population'].unique()

array([2477675, 2520970, 2565291, ...,     696,     700,     706])

In [598]:
dataset_pop.head()

Regions Location_code  Year  Total Population
0   WORLD           NaN  1950           2477675
1   WORLD           NaN  1951           2520970
2   WORLD           NaN  1952           2565291
3   WORLD           NaN  1953           2615251
4   WORLD           NaN  1954           2665307

In [599]:
dataset_pop['Total Population'].unique()

array([2477675, 2520970, 2565291, ...,     696,     700,     706])

In [600]:
dataset_pop['Total Population'].astype(int).round(1)

0        2477675
1        2520970
2        2565291
3        2615251
4        2665307
          ...   
20587        680
20588        690
20589        696
20590        700
20591        706
Name: Total Population, Length: 20592, dtype: int64

In [601]:
display(dataset_pop)

Regions Location_code  Year  Total Population
0          WORLD           NaN  1950           2477675
1          WORLD           NaN  1951           2520970
2          WORLD           NaN  1952           2565291
3          WORLD           NaN  1953           2615251
4          WORLD           NaN  1954           2665307
...          ...           ...   ...               ...
20587  Polynesia           NaN  2009               680
20588  Polynesia           NaN  2012               690
20589  Polynesia           NaN  2015               696
20590  Polynesia           NaN  2017               700
20591  Polynesia           NaN  2019               706

[20592 rows x 4 columns]

In [602]:
dataset_pop['Total Population'].unique()

array([2477675, 2520970, 2565291, ...,     696,     700,     706])

In [603]:
dataset_pop["Total Population"] = pd.to_numeric(dataset_pop["Total Population"], errors='coerce')
dataset_pop['Total Population'].unique()

array([2477675, 2520970, 2565291, ...,     696,     700,     706])

In [604]:
dataset_pop[["Total Population"]] = dataset_pop[["Total Population"]].astype(int).round()

In [605]:
dataset_pop["Total Population"].dtypes

dtype('int64')

In [606]:
dataset_pop["Location_code"].unique()

array([nan, 'SEN', 'URY', 'ARM', 'JAM', 'PNG', 'LAO', 'PRI', 'PAN', 'NOR',
       'LBY', 'HTI', 'DNK', 'NIC', 'GEO', 'PRY', 'SRB', 'MOZ', 'ISR',
       'BDI', 'PRT', 'BOL', 'BEL', 'AZE', 'SYR', 'HUN', 'NLD', 'UZB',
       'BFA', 'CUB', 'TUN', 'KHM', 'TZA', 'GHA', 'YEM', 'PRK', 'ARG',
       'KOR', 'MMR', 'POL', 'IRN', 'FRA', 'SVK', 'MLI', 'MYS', 'HND',
       'DZA', 'NER', 'BLR', 'CZE', 'SOM', 'IRQ', 'MAR', 'LVA', 'BWA',
       'KGZ', 'MNG', 'LBN', 'ALB', 'CAF', 'MDA', 'HRV', 'BEN', 'SLV',
       'ARE', 'KEN', 'GIN', 'AGO', 'SGP', 'AUT', 'PER', 'COM', 'STP',
       'KWT', 'LCA', 'WSM', 'ESH', 'BHR', 'NCL', 'GUM', 'MDV', 'ISL',
       'CUW', 'BRN', 'BLZ', 'VUT', 'BHS', 'MAC', 'SLB', 'MYT', 'BTN',
       'GUF', 'CPV', 'PYF', 'BRB', 'SUR', 'GLP', 'MTQ', 'GNQ', 'SWZ',
       'REU', 'GMB', 'LUX', 'MLT', 'DJI', 'FJI', 'MNE', 'TLS', 'QAT',
       'GAB', 'CYP', 'GNB', 'MUS', 'OMN', 'LSO', 'TTO', 'NAM', 'GUY',
       'GGY', 'IMN', 'JEY', 'ATG', 'ABW', 'DMA', 'VCT', 'BMU', 'KIR',
       'FSM', '

In [607]:
# change Nan in null to be able to run 'is not null'
dataset_pop["Location_code"].fillna("null")

0        null
1        null
2        null
3        null
4        null
         ... 
20587    null
20588    null
20589    null
20590    null
20591    null
Name: Location_code, Length: 20592, dtype: object

In [608]:
# divide countries from economic zones and continents
dataset_pop["Zone"] = dataset_pop.apply(lambda x: x["Regions"] if pd.isnull(x["Location_code"]) else "Not a Zone", axis=1)

In [609]:
# Check economic zones
dataset_pop["Zone"].unique()

array(['WORLD', 'Sub-Saharan Africa', 'Northern Africa and Western Asia',
       'Central and Southern Asia', 'Eastern and South-Eastern Asia',
       'Latin America and the Caribbean',
       'LATIN AMERICA AND THE CARIBBEAN',
       'Oceania (excluding Australia and New Zealand)', 'Not a Zone',
       'Australia/New Zealand', 'No income group available', 'OCEANIA',
       'Europe and Northern America', 'More developed regions',
       'Less developed regions', 'Least developed countries',
       'Less developed regions, excluding least developed countries',
       'Less developed regions, excluding China',
       'Land-locked Developing Countries (LLDC)',
       'Small Island Developing States (SIDS)', 'Central Asia',
       'Caribbean', 'High-income countries', 'Middle-income countries',
       'Upper-middle-income countries', 'Lower-middle-income countries',
       'Low-income countries', 'Northern Africa', 'AFRICA',
       'Eastern Africa', 'Western Africa', 'Melanesia', 'Micrones

In [610]:
# divide countries from economic zones and continents
dataset_pop["Country"] = dataset_pop.apply(lambda x: x["Regions"] if pd.notnull(x["Location_code"]) else "Nan", axis=1)

In [611]:
# Check countries
dataset_pop['Country'].unique()

array(['Nan', 'Senegal', 'Uruguay', 'Armenia', 'Jamaica',
       'Papua New Guinea', "Lao People's Democratic Republic",
       'Puerto Rico', 'Panama', 'Norway', 'Libya', 'Haiti', 'Denmark',
       'Nicaragua', 'Georgia', 'Paraguay', 'Serbia', 'Mozambique',
       'Israel', 'Burundi', 'Portugal',
       'Bolivia (Plurinational State of)', 'Belgium', 'Azerbaijan',
       'Syrian Arab Republic', 'Hungary', 'Netherlands', 'Uzbekistan',
       'Burkina Faso', 'Cuba', 'Tunisia', 'Cambodia',
       'United Republic of Tanzania', 'Ghana', 'Yemen',
       "Dem. People's Republic of Korea", 'Argentina',
       'Republic of Korea', 'Myanmar', 'Poland',
       'Iran (Islamic Republic of)', 'France', 'Slovakia', 'Mali',
       'Malaysia', 'Honduras', 'Algeria', 'Niger', 'Belarus', 'Czechia',
       'Somalia', 'Iraq', 'Morocco', 'Latvia', 'Botswana', 'Kyrgyzstan',
       'Mongolia', 'Lebanon', 'Albania', 'Central African Republic',
       'Republic of Moldova', 'Croatia', 'Benin', 'El Salvador',
 

In [612]:
display(dataset_pop)

Regions Location_code  Year  Total Population       Zone Country
0          WORLD           NaN  1950           2477675      WORLD     Nan
1          WORLD           NaN  1951           2520970      WORLD     Nan
2          WORLD           NaN  1952           2565291      WORLD     Nan
3          WORLD           NaN  1953           2615251      WORLD     Nan
4          WORLD           NaN  1954           2665307      WORLD     Nan
...          ...           ...   ...               ...        ...     ...
20587  Polynesia           NaN  2009               680  Polynesia     Nan
20588  Polynesia           NaN  2012               690  Polynesia     Nan
20589  Polynesia           NaN  2015               696  Polynesia     Nan
20590  Polynesia           NaN  2017               700  Polynesia     Nan
20591  Polynesia           NaN  2019               706  Polynesia     Nan

[20592 rows x 6 columns]

In [613]:
# Create a column Continent and add continents only.

dataset_pop['Continent'] = dataset_pop['Zone'].apply(lambda x:
                                                   'South America' if x == 'South America'
                                                   else 'North America' if x == 'NORTHERN AMERICA'
                                                   else 'Africa' if x =='AFRICA'
                                                   else 'Asia' if x =='ASIA'
                                                   else 'Europe' if x =='EUROPE'
                                                   else 'Oceania' if x =='OCEANIA'
                                            else "Not a continent")
display(dataset_pop)

Regions Location_code  Year  Total Population       Zone Country  \
0          WORLD           NaN  1950           2477675      WORLD     Nan   
1          WORLD           NaN  1951           2520970      WORLD     Nan   
2          WORLD           NaN  1952           2565291      WORLD     Nan   
3          WORLD           NaN  1953           2615251      WORLD     Nan   
4          WORLD           NaN  1954           2665307      WORLD     Nan   
...          ...           ...   ...               ...        ...     ...   
20587  Polynesia           NaN  2009               680  Polynesia     Nan   
20588  Polynesia           NaN  2012               690  Polynesia     Nan   
20589  Polynesia           NaN  2015               696  Polynesia     Nan   
20590  Polynesia           NaN  2017               700  Polynesia     Nan   
20591  Polynesia           NaN  2019               706  Polynesia     Nan   

             Continent  
0      Not a continent  
1      Not a continent  
2      Not a continent  
3      Not a continent  
4      Not a continent  
...                ...  
20587  Not a continent  
20588  Not a continent  
20589  Not a continent  
20590  Not a continent  
20591  Not a continent  

[20592 rows x 7 columns]

In [614]:
dataset_pop = dataset_pop.drop(columns=["Regions"])


In [615]:
display(dataset_pop)

Location_code  Year  Total Population       Zone Country  \
0               NaN  1950           2477675      WORLD     Nan   
1               NaN  1951           2520970      WORLD     Nan   
2               NaN  1952           2565291      WORLD     Nan   
3               NaN  1953           2615251      WORLD     Nan   
4               NaN  1954           2665307      WORLD     Nan   
...             ...   ...               ...        ...     ...   
20587           NaN  2009               680  Polynesia     Nan   
20588           NaN  2012               690  Polynesia     Nan   
20589           NaN  2015               696  Polynesia     Nan   
20590           NaN  2017               700  Polynesia     Nan   
20591           NaN  2019               706  Polynesia     Nan   

             Continent  
0      Not a continent  
1      Not a continent  
2      Not a continent  
3      Not a continent  
4      Not a continent  
...                ...  
20587  Not a continent  
20588  Not a continent  
20589  Not a continent  
20590  Not a continent  
20591  Not a continent  

[20592 rows x 6 columns]

In [616]:
dataset_pop['Year'] = dataset_pop['Year'].fillna(0)

In [617]:
dataset_pop["Year"] = dataset_pop["Year"].fillna(pd.NA).astype(pd.Int64Dtype())

In [618]:
display(dataset_pop)

Location_code  Year  Total Population       Zone Country  \
0               NaN  1950           2477675      WORLD     Nan   
1               NaN  1951           2520970      WORLD     Nan   
2               NaN  1952           2565291      WORLD     Nan   
3               NaN  1953           2615251      WORLD     Nan   
4               NaN  1954           2665307      WORLD     Nan   
...             ...   ...               ...        ...     ...   
20587           NaN  2009               680  Polynesia     Nan   
20588           NaN  2012               690  Polynesia     Nan   
20589           NaN  2015               696  Polynesia     Nan   
20590           NaN  2017               700  Polynesia     Nan   
20591           NaN  2019               706  Polynesia     Nan   

             Continent  
0      Not a continent  
1      Not a continent  
2      Not a continent  
3      Not a continent  
4      Not a continent  
...                ...  
20587  Not a continent  
20588  Not a continent  
20589  Not a continent  
20590  Not a continent  
20591  Not a continent  

[20592 rows x 6 columns]

In [619]:
dataset_pop.to_csv(r"/Users/rossana/Desktop/demoday/Population_growth_def.csv")